### ISSUE TITLE
Provider clearer/thourough instructions

### ISSUE THREAD

**Issue by koobs** [SteamOnFreeBSD/SteamOnFreeBSD#4]
A user [tweeted a negative experience](https://twitter.com/codydragondude/status/762231171052732417) after attempting to install SteamOnFreeBSD.

It seems the installation got stuck at the `install.sh` stage with the following error repeated:

`install.sh: doas: not found`

The screenshot/image provided displays the installation process and commands that were run

While `doas` is listed as a command to run in the README, it may not be clear to some users what it is, nor how to acquire it. Additionally, the user reports continued errors even after installing the security/doas port.

Can this requirement be removed in favour of `sudo` or a note saying that commands should be run as root. If not, can the installation instuctions in the README be tested (with newbies in mind) and updated accordingly

![cpp9mw_vuaaprwc](https://cloud.githubusercontent.com/assets/1011612/17462384/546673d0-5cee-11e6-988f-64eaec80b9b9.jpg)

Edit: Thank you for working on getting Steam to run on FreeBSD

**Comment by SteamOnFreeBSD** [comment]
Ok!!
"pkg install doas" added  in README
