### ISSUE TITLE
Install fails

### ISSUE THREAD

**Issue by archfan** [SteamOnFreeBSD/SteamOnFreeBSD#5]
Just tested this on my FreeBSD 11.0-beta4 system with a NVIDIA GTX 1070 graphics card. Unfortunately the installer fails.

Attached below is the log of the terminal output.
[error.txt](https://github.com/SteamOnFreeBSD/SteamOnFreeBSD/files/414600/error.txt)

**Comment by archfan** [comment]
You might want to add two extra dependencies to your list: rpm2cpio, deb2targz

**Comment by archfan** [comment]
Also a few packages are outdated for x86_64. Below are the latest ones:

libcurl3_7.35.0-1ubuntu2.8_amd64.deb
libnss3_3.21-1ubuntu4_amd64.deb
libnspr4_4.10.2-1ubuntu1_amd64.deb
libcurl3-gnutls_7.35.0-1ubuntu2.8_amd64.deb

**Comment by SteamOnFreeBSD** [comment]
add dependency and update listpackages_x86_64

**Comment by koobs** [comment]
@archfan If this issue has been resolved, please close :)
