### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by mnd999** [SteamOnFreeBSD/SteamOnFreeBSD#8]
Script fails:

64bit: 

`fetch: http://de.archive.ubuntu.com/ubuntu/pool/main/g/gdk-pixbuf/libgdk-pixbuf2.0-0_2.30.7-0ubuntu1.2_amd64.deb: Not Found
fetch: http://de.archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.0.0_1.0.1f-1ubuntu2.19_amd64.deb: Not Found
fetch: http://de.archive.ubuntu.com/ubuntu/pool/main/libg/libgcrypt11/libgcrypt11_1.5.3-2ubuntu4.3_amd64.deb: Not Found
fetch: http://de.archive.ubuntu.com/ubuntu/pool/main/o/openssl/openssl_1.0.1f-1ubuntu2.19_amd64.deb: Not Found
tar: Error opening archive: Failed to open 'deb_x86_64/libgdk-pixbuf2.0-0_2.30.7-0ubuntu1.2_amd64.deb'
tar: Error opening archive: Failed to open 'deb_x86_64/libssl1.0.0_1.0.1f-1ubuntu2.19_amd64.deb'
tar: Error opening archive: Failed to open 'deb_x86_64/libgcrypt11_1.5.3-2ubuntu4.3_amd64.deb'
tar: Error opening archive: Failed to open 'deb_x86_64/openssl_1.0.1f-1ubuntu2.19_amd64.deb'
tar: Error opening archive: Failed to open 'deb_x86_64/libgdk-pixbuf2.0-0_2.30.7-0ubuntu1.2_amd64.tar.*'
tar: Error opening archive: Failed to open 'deb_x86_64/libssl1.0.0_1.0.1f-1ubuntu2.19_amd64.tar.*'
tar: Error opening archive: Failed to open 'deb_x86_64/libgcrypt11_1.5.3-2ubuntu4.3_amd64.tar.*'
tar: Error opening archive: Failed to open 'deb_x86_64/openssl_1.0.1f-1ubuntu2.19_amd64.tar.*'
`

32bit:

`fetch: http://de.archive.ubuntu.com/ubuntu/pool/main/g/gdk-pixbuf/libgdk-pixbuf2.0-0_2.30.7-0ubuntu1.2_i386.deb: Not Found
fetch: http://de.archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.0.0_1.0.1f-1ubuntu2.19_i386.deb: Not Found
fetch: http://de.archive.ubuntu.com/ubuntu/pool/main/o/openssl/openssl_1.0.1f-1ubuntu2.19_i386.deb: Not Found
tar: Error opening archive: Failed to open 'deb/libgdk-pixbuf2.0-0_2.30.7-0ubuntu1.2_i386.deb'
tar: Error opening archive: Failed to open 'deb/libssl1.0.0_1.0.1f-1ubuntu2.19_i386.deb'
tar: Error opening archive: Failed to open 'deb/openssl_1.0.1f-1ubuntu2.19_i386.deb'
tar: Error opening archive: Failed to open 'deb/libgdk-pixbuf2.0-0_2.30.7-0ubuntu1.2_i386.tar.*'
tar: Error opening archive: Failed to open 'deb/libssl1.0.0_1.0.1f-1ubuntu2.19_i386.tar.*'
tar: Error opening archive: Failed to open 'deb/openssl_1.0.1f-1ubuntu2.19_i386.tar.*'
`

**Comment by SteamOnFreeBSD** [comment]
Fixed
